#!/bin/bash
# Sabayon lxc image builder script
# mudler@sabayon.org
# credits for lxc image structure goes to https://github.com/saghul/lxd-alpine-builder
set -e
HOST_ARCH="${HOST_ARCH:-amd64}"
ARCH="${ARCH:-`uname -m`}"
IMAGE="${IMAGE:-sabayon/base-amd64}"
DISTRO="${DISTRO:-Sabayon}"
OS="${OS:-sabayon}"
RELEASE="${RELEASE:-16}"
UNPRIVILEGED="${UNPRIVILEGED:-0}"
STAGING_DIR="${STAGING_DIR:-`pwd`}"
IMAGE_DESCR=""

create_metadata() {
   release_epoch=$(date +%s)

	if [ -z "${IMAGE_DESCR}" ] ; then
      release_date=$(date +%Y%m%d_%H:%M)
      IMAGE_DESCR="$DISTRO $RELEASE ($release_date)"
   fi

   cat <<EOF > metadata.yaml
{
	"architecture": "$ARCH",
	"creation_date": $release_epoch,
	"properties": {
	  "description": "$IMAGE_DESCR",
	  "os": "$OS",
	  "release": "$RELEASE",
	},
	"templates": {
	  "/etc/hosts": {
	    "template": "hosts.tpl",
	    "when": [
	      "create",
	    ]
	  },
	  "/etc/hostname" : {
	    "template": "hostname.tpl",
	    "when": [
	      "create",
	    ]
	  },
	}
}
EOF

   mkdir -p templates

   cat <<EOF > templates/hostname.tpl
{{ container.name }}
EOF

   cat <<EOF > templates/hosts.tpl
127.0.0.1   localhost
127.0.1.1   {{ container.name }}
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

   return 0
}

package_image() {
   release_date=$(date +%Y%m%d_%H%M)

   tar -zcf $OS-$RELEASE-$ARCH-$release_date.tar.gz --numeric-owner metadata.yaml templates rootfs
   rm -f metadata.yaml
   rm -rf templates
   rm -rf rootfs

   return 0
}


update_docker_companion() {

	type docker-companion >/dev/null 2>&1 || {
		echo >&2 "Fetching docker-companion for you, and placing it under bin/"
		curl -s https://api.github.com/repos/mudler/docker-companion/releases/latest \
			| grep "browser_download_url.*${HOST_ARCH}" \
			| cut -d : -f 2,3 \
			| tr -d \" \
			| wget -i - -N -O docker-companion
		chmod +x docker-companion
	}
}


help_msg() {

   echo "create_image:
Script for create LXD image from Docker image.

-h|--help        This message.
--arch           Set target ARCH. This field is not same of Gentoo ARCH variable.
                 MUST be set based of machine hardware.
                 Example armv7l (for BananaPi), x86_64 (for x86 64bit platform).
                 Default value is: \`uname -m\`.
--host-arch      Set arch of the host where is running docker Server.
                 Default value is: x86_64.
--unprivileged   When this option is enable some activities are done on target
                 image for permit running of the image under unprivileged mode.
                 It's usable only for Sabayon/Gentoo Image with SystemD.
                 Default is disable and created image is for privileged mode.
--stagingdir     Set staging directory where unpack docker image and create
                 tarball. Default is \`pwd\`.
--image          Docker image to use as source.
                 Default is: sabayon/base-amd64
--image-descr    Set image description string.
                 Default is: \$DISTRO \$RELEASE (\$release_date)

Some options could be set also as environment variables:
HOST_ARCH        Alternative to --host-arch option.
ARCH             Alternative to --arch option.
IMAGE            Alternative to --image option.
DISTRO           Identify distro of the image. Default is: Sabayon
OS               Identify OS of the image. Default is: sabayon
RELEASE          Identify Release of the distro. Default is: 16
                 This variable is used only when IMAGE_DESCR or --image-descr
                 is not used.
UNPRIVILEGED     Alternative to --unprivileged option.
STAGING_DIR      Alternative to --stagingdir option.
IMAGE_DESCR      Alternative to --image-descr option.

NOTE: This script MUST be execute as root.
"
}

parse_args() {

   local short_opts="h"
   local long_opts="help arch: host-arch: unprivileged stagingdir: image-descr: image:"

   $(set -- $(getopt -u -q -a -o "$short_opts" -l "$long_opts" -- "$@")) 

   while [ $# -gt 0 ] ; do
      case "$1" in

         -h|--help)
            help_msg
            exit 1
            ;;
         --arch)
            ARCH="$2"
            shift
            ;;
         --host-arch)
            HOST_ARCH="$2"
            shift
            ;;
         --unprivileged)
            UNPRIVILEGED=1
            ;;
         --stagingdir)
            STAGING_DIR="$2"
            shift
            ;;
         --image-descr)
            IMAGE_DESCR="$2"
            shift
            ;;
         --image)
            IMAGE="$2"
            shift
            ;;
         --)
            ;;
         *)
            echo "Invalid parameter $1."
            exit 1
            ;;

      esac

      shift
   done

   return 0
}

unprivileged_rootfs() {

   pushd ${STAGING_DIR}/rootfs/etc/systemd/system

   # Disable systemd-journald-audit.socket because it seems that doesn't
   # start correctly on unprivileged container
   ln -s /dev/null systemd-journald-audit.socket

   # Disable systemd-remount-fs.service because on unprivileged container
   # systemd can't remount filesystem
   ln -s /dev/null systemd-remount-fs.service

   # Clean journal directory (to avoid permission errors)
   rm -rf ${STAGING_DIR}/rootfs/var/log/journal/

   # Change execution of service systemd-sysctl to avoid errors.
   mkdir systemd-sysctl.service.d
   cat <<EOF > systemd-sysctl.service.d/00gentoo.conf
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-sysctl  --prefix=/etc/sysctl.d/
EOF

   # Disable mount of hugepages
   ln -s /dev/null dev-hugepages.mount

   popd

   return 0
}

main() {

   parse_args "$@"

   if [ "$(id -u)" != "0" ]; then
      echo "This script must be run as root" 1>&2
      exit 1
   fi

   update_docker_companion

   [[ -e "docker-companion" ]] \
      && ./docker-companion --pull unpack "${IMAGE}" ${STAGING_DIR}/rootfs \
      || docker-companion --pull unpack "${IMAGE}" ${STAGING_DIR}/rootfs

   pushd ${STAGING_DIR}

   create_metadata || die "Failed to create metadata"

   if [ ${UNPRIVILEGED} -eq 1 ] ; then
      unprivileged_rootfs || die "Error on unprivileged rootfs"
   fi

   package_image || die "Failed to package image"

   popd

   exit 0

}

main "$@"


# vim: ts=3 sw=3 expandtab filetype=sh
